import nodemailer from "nodemailer";
import type { ScoredJob } from "../types.js";
import { escapeAttr } from "../utils.js";
function htmlEscape(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
export function buildEmailHtml(jobs: ScoredJob[], stats: {
    period: string;
    found: number;
    newCount: number;
}): string {
    const rows = jobs
        .slice(0, 10)
        .map((j, i) => `
      <tr>
        <td style="padding:12px;border:1px solid #e5e7eb">
          <strong>${i + 1}. ${htmlEscape(j.title)}</strong><br/>
          ${htmlEscape(j.company)} — ${htmlEscape(j.location ?? "—")} — <strong>${j.score}% match</strong><br/>
          <small>${htmlEscape(j.reasons.join(" • "))}</small><br/>
          <small>Skills: ${htmlEscape(j.matchedSkills.slice(0, 5).join(" • ") || "—")}</small><br/>
          <a href="${escapeAttr(j.url)}">Apply →</a>
          ${j.gaps.length ? `<br/><small style="color:#6b7280">Gaps: ${htmlEscape(j.gaps.join(", "))}</small>` : ""}
        </td>
      </tr>`)
        .join("");
    return `
  <h2>🚀 Job Hunt Report</h2>
  <p>Period: ${htmlEscape(stats.period)} — Found: ${stats.found} relevant | New: ${stats.newCount}</p>
  ${jobs.length === 0 ? "<p>No new high-quality matches.</p>" : `<table style="border-collapse:collapse;width:100%">${rows}</table>`}
  <p style="color:#6b7280;font-size:12px">Generated by job-hunter</p>`;
}
export async function sendEmail(jobs: ScoredJob[], stats: {
    period: string;
    found: number;
    newCount: number;
}): Promise<void> {
    const html = buildEmailHtml(jobs, stats);
    const subject = `Job Hunt Report: ${stats.newCount} new — ${jobs.length} top matches`;
    const resendKey = process.env.RESEND_API_KEY;
    if (resendKey && process.env.RESEND_TO) {
        const res = await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: {
                Authorization: `Bearer ${resendKey}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                from: process.env.RESEND_FROM ?? "job-hunter@resend.dev",
                to: process.env.RESEND_TO,
                subject,
                html,
            }),
            signal: AbortSignal.timeout(15000),
        });
        if (!res.ok)
            throw new Error(`Resend failed ${res.status}: ${await res.text()}`);
        console.log("[email] Sent via Resend");
        return;
    }
    const smtpHost = process.env.SMTP_HOST;
    if (smtpHost && process.env.SMTP_USER && process.env.SMTP_PASS && process.env.EMAIL_TO) {
        const port = Number(process.env.SMTP_PORT ?? 587);
        const transport = nodemailer.createTransport({
            host: smtpHost,
            port,
            secure: port === 465,
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS,
            },
        });
        await transport.sendMail({
            from: process.env.EMAIL_FROM ?? process.env.SMTP_USER,
            to: process.env.EMAIL_TO,
            subject,
            html,
        });
        console.log("[email] Sent via SMTP");
        return;
    }
    console.log("[email] Skipped — set RESEND_API_KEY+RESEND_TO or SMTP_HOST+SMTP_USER+SMTP_PASS+EMAIL_TO");
}
