import type { ScoredJob } from "../types.js";

function htmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function buildEmailHtml(jobs: ScoredJob[], stats: { period: string; found: number; newCount: number }): string {
  const rows = jobs
    .slice(0, 10)
    .map(
      (j, i) => `
      <tr>
        <td style="padding:12px;border:1px solid #e5e7eb">
          <strong>${i + 1}. ${htmlEscape(j.title)}</strong><br/>
          ${htmlEscape(j.company)} — ${htmlEscape(j.location ?? "—")} — <strong>${j.score}% match</strong><br/>
          <small>${htmlEscape(j.reasons.join(" • "))}</small><br/>
          <small>Skills: ${htmlEscape(j.matchedSkills.slice(0, 5).join(" • ") || "—")}</small><br/>
          <a href="${j.url}">Apply →</a>
          ${j.gaps.length ? `<br/><small style="color:#6b7280">Gaps: ${htmlEscape(j.gaps.join(", "))}</small>` : ""}
        </td>
      </tr>`,
    )
    .join("");

  return `
  <h2>🚀 Job Hunt Report</h2>
  <p>Period: ${htmlEscape(stats.period)} — Found: ${stats.found} relevant | New: ${stats.newCount}</p>
  ${jobs.length === 0 ? "<p>No new high-quality matches.</p>" : `<table style="border-collapse:collapse;width:100%">${rows}</table>`}
  <p style="color:#6b7280;font-size:12px">Generated by job-hunter</p>`;
}

export async function sendEmail(jobs: ScoredJob[], stats: { period: string; found: number; newCount: number }): Promise<void> {
  const resendKey = process.env.RESEND_API_KEY;
  const smtpHost = process.env.SMTP_HOST;

  const html = buildEmailHtml(jobs, stats);
  const subject = `Job Hunt Report: ${stats.newCount} new — ${jobs.length} top matches`;

  // Prefer Resend if configured
  if (resendKey && process.env.RESEND_TO) {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: process.env.RESEND_FROM ?? "job-hunter@resend.dev",
        to: process.env.RESEND_TO,
        subject,
        html,
      }),
    });
    if (!res.ok) throw new Error(`Resend failed ${res.status}: ${await res.text()}`);
    console.log("[email] Sent via Resend");
    return;
  }

  if (smtpHost && process.env.SMTP_USER && process.env.EMAIL_TO) {
    // Lazy import nodemailer only if needed — keep deps minimal
    // For MVP we use fetch-based SMTP alternative or log
    console.log("[email] SMTP configured but nodemailer not bundled — set RESEND_API_KEY or integrate nodemailer");
    console.log(`[email] Would send to ${process.env.EMAIL_TO}: ${subject}`);
    return;
  }

  if (!resendKey && !smtpHost) {
    console.log("[email] Skipped — no email env set");
    if (process.env.DRY_RUN === "true") console.log(html);
    return;
  }
}
